### PR TITLE
Add ContainedIn Method

### PR DESCRIPTION
**Pull request by sescobb27**
This feature is how we can query elements in DB who match certain criteria (e.g)

```ruby
Customer.where.contained_in_array(categories: categories).find_in_batches
```

generating the following query
```sql
SELECT "customers".*
FROM "customers"
WHERE ("customers"."categories" <@ '{Disco,Bar,Restaurant}')
ORDER BY "customers"."id"
ASC LIMIT 1000
```

### CODE REVIEW

**Comment by sescobb27** [comment]
```
/home/ubuntu/postgres_ext/vendor/bundle/ruby/1.9.1/gems/activerecord-4.2.3/lib/active_record/connection_adapters/connection_specification.rb:248:in `resolve_symbol_connection': 'test' database is not configured. Available: [] (ActiveRecord::AdapterNotSpecified)
```
not sure what does it mean? do I need to setup PR test database?

**Comment by nathancolgate** [comment]
@sescobb27 Thanks for taking the time to write this. It worked perfectly for me.

Until this gets merged in, I've put all of your code in an [initializer](https://gist.github.com/nathancolgate/dc36ffdc6832836eaa7a52371c3868e8) in my app.

**Comment by sescobb27** [comment]
Thank you, at least is helpful to someone. sadly I don't think this PR is not going to make it, it has been open for almost 1 year, and I don't know how to fix that test (it worked on my desktop but I don't have access to circleci configuration).
Maybe someone can point me how to fix it or what it needs to get this PR merged with master. cc @danmcclain

**Comment by edpaget** [comment]
Looks good to me thanks @sescobb27

**Pull request merged**
