### PR TITLE
Allow CTE to be merged by ActiveRecord::Relation::Merger

### LINKED ISSUE #178: ActiveRecord does not keep the CTE part (ie the "WITH ...") on a merge
Simple example : when merging a ActiveRecord relation with a CTE, the produced query does not keep the `WITH` part :
   ~~~ruby
User.where(id:1).merge(User.with(cte: 'SELECT 1 as id'))
# SELECT "users".* FROM "users" WHERE "users"."id" = 1
   ~~~

If we reverse the merged query with the original one, it works as expected :
   ~~~ruby
User.with(cte: 'SELECT 1 as id').merge(User.where(id:1))
# WITH "cte" AS (SELECT 1 as id) SELECT "users".* FROM "users" WHERE "users"."id" = 1
   ~~~

Are you okay to re-implement (part of) `ActiveRecord::Relation::HashMerger`  ( [rails/rails/activerecord/lib/active_record/relation/merger.rb](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/merger.rb) ) to solve this issue ?

It seems we only need to add `:with` in the `NORMAL_VALUES` array on https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/merger.rb#L53

### PR DESCRIPTION
**Pull request by chtitux**
It fixes #178

### CODE REVIEW

**Comment by edpaget** [comment]
Looks good to me. Thank you very much. I'll make a release later today.

**Comment by chtitux** [comment]
Thank you very much for your merge. By the way, have you a date for the next release ?

Thank you very much for your project,
Regards

**Comment by edpaget** [comment]
Sorry I realized I don't have permissions to publish to our gem. I'm going to try to contact to the original author have him add me.

**Comment by edpaget** [comment]
This has been published as `postgres_ext 3.0.0` since the change may break existing code that assumed the old behaviour.

**Comment by mattbrictson** [comment]
I notice this was released with a major version change of 2.4.1 to 3.0.0. Does this mean that there is a backwards-compatibility issue or other breaking changes that I should be concerned about? I checked the CHANGELOG and there was no mention of it.

Just wondering because major semver changes make me nervous. :wink:

**Comment by mattbrictson** [comment]
> This has been published as postgres_ext 3.0.0 since the change may break existing code that assumed the old behaviour.

Ah sorry, I should have read this thread more closely. So the only backwards-compatibility concern is for those using CTE with merge and relying on the old behavior? If I am not using CTE with merge than I should be OK.

**Comment by chtitux** [comment]
Thank you very much to both of you, for the new version, and for this gem!

**Pull request merged**
